### ISSUE TITLE
Vida pessoal

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#1]
Detalhes da vida pessoal, tais como: 

- onde e quando nasceu?
- quem eram os pais? com o que eles trabalhavam?
- como foi sua infância/adolescência?
- como era sua personalidade (tímido, extrovertido, etc)?
- o que mais gostava de fazer?
- qualquer outra informação que considere relevante sobre sua vida pessoal.

Para realizar essa _issue_, utilize o arquivo `stallman/vida-pessoal.md`

**Comment by thiagoluigi7** [comment]
Boa noite, eu e meu grupo (Matheus Matias e Tiago de Oliveira Carlos) desejamos trabalhar nesta issue

**Comment by paulojunior-ufla** [comment]
Olá, @thiagoluigi7. Podem trabalhar nela.
