### ISSUE TITLE
Álbum de fotos

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#10]
Apresente as principais fotos desta personalidade, disponíveis publicamente, com comentários que descrevam onde, quando e o que estava ocorrendo no momento em que a foto foi tirada.

Para realizar essa _issue_, utilize o arquivo `stallman/fotos.md`

**Comment by eribito** [comment]
Nosso grupo tem interesse em realizar essa tarefa

**Comment by paulojunior-ufla** [comment]
Olá, @eribito. Ok, a _issue_ está com vocês.
