### ISSUE TITLE
Prêmios e reconhecimento

### ISSUE THREAD

**Issue by thomazdevmaster** [ufla-gcc259/personalidades-sl#13]
Nosso grupo tem interesse em falar sobre os **prêmios e reconhecimentos** pela sua contribuição à sociedade, outorgados a Richard Stallman, Poderíamos criar um arquivo com o nome de `Prêmios-e-reconhecimentos.md`
Caso seja aceita a proposta o grupo é composto por:
* João Vitor Soares Rezende
* Pedro Henrique de Menezes
* Thomaz Flanklin de Souza Jorge

**Comment by thomazdevmaster** [comment]
@paulojunior-ufla , poderia verificar se tem essa possibilidade? Pois já realizamos algumas pesquisas.

**Comment by paulojunior-ufla** [comment]
Olá, @ThomazSIUFLA. Gostei bastante da ideia. Pode seguir com esse tema sim.

**Comment by thomazdevmaster** [comment]
Ok, seguiremos com essa Issue então!
