### ISSUE TITLE
Formação acadêmica

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#2]
Detalhes sobre sua formação acadêmica, tais como: 

- quando e onde estudou (ensino básico, faculdade)?
- quais suas matérias favoritas na escola/faculdade?
- qual curso escolheu fazer e quando se formou?
- quais cursos de pós-graduação fez, quando e onde?
- quais foram suas principais contribuições acadêmicas?
- qualquer outra informação que considere relevante sobre sua formação acadêmica

Para realizar essa _issue_, utilize o arquivo `stallman/formacao-academica.md`

**Comment by MrDuckBr** [comment]
Boa noite, há alguém trabalhando nesta issue? Caso não gostaria de trabalhar nela.

**Comment by paulojunior-ufla** [comment]
Olá, @MrDuckBr . Está com você!
