### ISSUE TITLE
Vida pessoal

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#27]
Detalhes da vida pessoal, tais como:

- onde e quando nasceu?
- quem eram os pais? com o que eles trabalhavam?
- como foi sua infância/adolescência?
- como era sua personalidade (tímido, extrovertido, etc)?
- o que mais gostava de fazer?
- qualquer outra informação que considere relevante sobre sua vida pessoal.

Para realizar essa issue, utilize o arquivo `linus/vida-pessoal.md`

**Comment by HarturFranco** [comment]
Boa tarde, meu grupo (Arthur Franco, Thiago Salles e João Paulo Paiva) gostaríamos de trabalhar nesta issue.

**Comment by paulojunior-ufla** [comment]
Olá, @HarturFranco. Ok, bom trabalho para vocês. Fico aguardado seu PR...
