### ISSUE TITLE
Formação acadêmica

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#28]
Detalhes sobre sua formação acadêmica, tais como:

- quando e onde estudou (ensino básico, faculdade)?
- quais suas matérias favoritas na escola/faculdade?
- qual curso escolheu fazer e quando se formou?
- quais cursos de pós-graduação fez, quando e onde?
- quais foram suas principais contribuições acadêmicas?
- qualquer outra informação que considere relevante sobre sua formação acadêmica

Para realizar essa issue, utilize o arquivo `linus/formacao-academica.md`

**Comment by Nxxxlxs** [comment]
Olá, meu grupo gostaria de trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @Nxxxlxs. Ótimo, obrigado pelo interesse. Fico aguardando a contribuição de vocês.
