### ISSUE TITLE
Carreira profissional

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#29]
Detalhes da vida profissional, tais como:

- onde e quando trabalhou profissionalmente?
- quais funções desempenhava?
- quais foram suas principais contribuições profissionais?
- qualquer outra informação que considere relevante sobre sua vida profissional

Para realizar essa issue, utilize o arquivo `linus/carreira.md`

**Comment by erick-escape** [comment]
Olá, Paulo!
Meu grupo gostaria de trabalhar nesta issue.

**Comment by paulojunior-ufla** [comment]
Olá, @erick-escape. Tudo bem! Bom trabalho pra vocês.
