### ISSUE TITLE
Carreira profissional

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#3]
Detalhes da vida profissional, tais como: 

- onde e quando trabalhou profissionalmente?
- quais funções desempenhava?
- quais foram suas principais contribuições profissionais?
- qualquer outra informação que considere relevante sobre sua vida profissional

Para realizar essa _issue_, utilize o arquivo `stallman/carreira.md`

**Comment by paulorsv01** [comment]
Opa, boa noite @paulojunior-ufla. Gostaria de trabalhar nesta issue. Posso?

**Comment by paulojunior-ufla** [comment]
Olá, @paulorsv01. Claro, fique à vontade!

**Comment by paulorsv01** [comment]
Obrigado! 

---

Para possíveis interessados: a princípio não tenho uma dupla/um grupo. Então caso tenham interesse em montar uma equipe para trabalhar em conjunto nesta issue é só mandar um comentário aqui me marcando que podemos combinar. 

<img src="https://media0.giphy.com/media/ErZ8hv5eO92JW/giphy.gif" width="50%"/>

**Comment by paulojunior-ufla** [comment]
Boa iniciativa, @paulorsv01

**Comment by Pedro-Carvalho-Pereira** [comment]
Boa tarde @paulorsv01 , tenho interesse em trabalhar nessa issue, posso entrar no seu grupo?

**Comment by paulorsv01** [comment]
> Boa tarde @paulorsv01 , tenho interesse em trabalhar nessa issue, posso entrar no seu grupo?

Pode sim, claro!
