### ISSUE TITLE
O Linux

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#30]
Detalhes sobre sua relação com o movimento de Software Livre, em especial sobre o projeto do Kernel do Linux:

- o que é o projeto?
- qual é ou quais são seus objetivos?
- como ele se relaciona com o Software Livre?
- qual o status do projeto atualmente?

Para realizar essa issue, utilize o arquivo `linus/linux.md`

**Comment by lyviaAbreu** [comment]
Meu grupo (Lyvia Abreu, Gabriel Henrique, Ghabriell Luz, Mateus Augusto) gostaria de colaborar com essa issue

**Comment by paulojunior-ufla** [comment]
Olá, @lyviaAbreu. Tudo bem, podem prosseguir...
