### ISSUE TITLE
O Git

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#31]
Detalhes sobre sua relação com o movimento de Software Livre, em especial sobre o projeto do sistema de controle de versões Git:

- o que é o projeto?
- qual é ou quais são seus objetivos?
- como ele se relaciona com o Software Livre?
- qual o status do projeto atualmente?

Para realizar essa issue, utilize o arquivo `linus/git.md`

**Comment by StenioHenrique** [comment]
Meu grupo (Stenio Silva e Vitória Alvim) gostaria de resolver essa issue.

**Comment by paulojunior-ufla** [comment]
Ok, @StenioHenrique. Fico aguardando o PR de vocês...
