### ISSUE TITLE
Polêmicas

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#32]
Apresente as principais polêmicas em que a personalidade esteve envolvida, seja no aspecto pessoal, acadêmico ou profissional. Tente ser o mais objetivo possível, citando apenas fatos comprovados e publicamente divulgados.

Para realizar essa issue, utilize o arquivo `linus/polemicas.md`

**Comment by Dezena14** [comment]
Olá! Meu grupo gostaria de fazer essa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @Dezena14. Tudo bem, fico aguardando as contribuições de vocês...
