### ISSUE TITLE
Curiosidades

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#33]
Apresente as principais curiosidades acerca desta personalidade, seja no aspecto pessoal, acadêmico ou profissional.

Para realizar essa issue, utilize o arquivo `linus/curiosidades.md`

**Comment by Rafael1050** [comment]
Meu grupo (Rafael Arriel, Renan Fernandes) gostaria de resolver essa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @Rafael1050. Perfeito! Fico aguardando o PR...
