### ISSUE TITLE
Álbum de fotos

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#34]
Apresente as principais fotos desta personalidade, disponíveis publicamente, com comentários que descrevam onde, quando e o que estava ocorrendo no momento em que a foto foi tirada.

Para realizar essa issue, utilize o arquivo `linus/fotos.md`

**Comment by JulianoA28** [comment]
Boa noite,
Nosso grupo, Chrystian, Israel, Luis Wagner e eu, gostaríamos de trabalhar nesta issue.

**Comment by paulojunior-ufla** [comment]
Olá, @JulianoA28. Ok, fico aguardando a contribuição de vocês.
