### ISSUE TITLE
Prêmios e reconhecimento

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#35]
Apresente os principais prêmios e reconhecimentos recebidos por esta personalidade, disponíveis publicamente, com comentários que descrevam onde e quando ocorreu a premiação e sobre qual tipo de contribuição ela se referia.

Para realizar essa issue, utilize o arquivo `linus/premios-e-reconhecimentos.md`

**Comment by luis131313** [comment]
Olá, boa noite!
Meu grupo (Luis Fernando, Vitor Tenório, Iago Manoel e Vinícius Caputo) gostaria de realizar essa issue, desde já grato pela atenção.

**Comment by paulojunior-ufla** [comment]
Olá, @luis131313. Tudo bem, fico aguardando a contribuição de vocês.
