### ISSUE TITLE
O projeto GNU

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#4]
Detalhes sobre sua relação com o movimento de Software Livre, em especial sobre o projeto GNU: 

- o que é o projeto?
- qual é ou quais são seus objetivos?
- como ele se relaciona com o Software Livre?
- qual o status do projeto atualmente?

Para realizar essa _issue_, utilize o arquivo `stallman/projeto-gnu.md`

**Comment by luis-saes** [comment]
Boa noite, eu e minha dupla temos interesse em realizar esta issue, há alguém trabalhando nela?

**Comment by paulojunior-ufla** [comment]
Olá, @luis-saes. Podem prosseguir.
