### ISSUE TITLE
Produções (livros, artigos, programas, etc.)

### ISSUE THREAD

**Issue by joaoabjr** [ufla-gcc259/personalidades-sl#44]
A ideia proposta para a issue é descrever e ilustrar sobre as principais obras de Linus Torvalds, desde livros, artigos, programas e outras produções. 
A issue será desenvolvida por mim (João Almeida) e Victor Cabral, e para tal desenvolvimento utilizaremos o arquivo `linus/producoes.md`
Obrigado, Paulo! Aguardamos a aprovação da ideia :)

**Comment by paulojunior-ufla** [comment]
Olá, @joaoabjr. É uma ótima ideia. Podem dar prosseguimento!

**Comment by Viniciud** [comment]
Olá, @joaoabjr. Eu poderia ajudá-los a contribuir nessa issue?

**Comment by paulojunior-ufla** [comment]
Aí @joaoabjr, se for possível, dê uma mão para o @Viniciud... Valeu!

**Comment by joaoabjr** [comment]
> Olá, @joaoabjr. Eu poderia ajudá-los a contribuir nessa issue?

Claro que pode, Vinícius! 

Se quiser pode se encarregar da parte de artigos, trabalhos acadêmicos e outros documentos de produção do Linus.

Se quiser trocar uma idéia pode me mandar um e-mail que te passo meu número: joaoalmeidabarbosajr@gmail.com

Abraço!
