### ISSUE TITLE
História

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#49]
Detalhes da história da fundação, tais como:

* como e quando surgiu?
* quais as razões (motivações) levaram à sua existência?
* qual a missão, visão e valores da fundação?
* como a fundação se mantinha financeiramente no início? É assim até os dias atuais?
* quais foram os seus fundadores?
* por que esse nome Apache?

Para realizar essa _issue_, utilize o arquivo `apache/historia.md`

**Comment by mJR-exe** [comment]
Eu (Maurício Júnior), Fabrício Smargiasse, Gustavo Marzoque e Pedro Garcia gostaríamos de trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
@mJR-exe, combinado! Aguardo o PR de vocês.
