### ISSUE TITLE
A FSF (Free Software Foundation)

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#5]
Detalhes sobre sua relação com o movimento de Software Livre, em especial sobre a FSF (_Free Software Foundation_): 

- o que é a FSF?
- qual é ou quais são seus objetivos?
- como ela se relaciona com o Software Livre?
- qual o status do projeto atualmente?

Para realizar essa _issue_, utilize o arquivo `stallman/fsf.md`

**Comment by wenderlemes** [comment]
Boa tarde! Se não houver problemas, meu grupo tem interesse em trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @wenderlemes. Ok, bom trabalho pra vocês!
