### ISSUE TITLE
Pessoas envolvidas

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#50]
Descrição sucinta sobre a vida das principais pessoas envolvidas com o projeto, tais como:

* quem e quando atuou na fundação?
* qual cargo ocupava?
* qual a sua importância para a história da fundação e para o mundo software livre como um todo?

Para realizar essa _issue_, utilize o arquivo `apache/pessoas.md`

**Comment by ronaldsouza77** [comment]
Olá, meu grupo gostaria de trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @ronaldsouza77. Ok. Aguardo o PR de vocês.
