### ISSUE TITLE
Apache HTTP server

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#51]
Apresente detalhes sobre o projeto, tais como:

* o que é o projeto?
* qual é ou quais são seus objetivos?
* qual a importância desse projeto para a fundação Apache e para o Software Livre como um todo?
* qual o status do projeto atualmente?
* qual a página oficial do projeto?

Para realizar essa _issue_, utilize o arquivo `apache/server.md`

**Comment by LeoJunioYuri** [comment]
Oi, professor.
Meu grupo tem interesse nessa Issue (Leonardo Basso, João Veronezi, Rafael Moura e Mateus Peternelli).
Atenciosamente,
Leonardo

**Comment by paulojunior-ufla** [comment]
Olá, @LeoJunioYuri. Perfeito, aguardo o PR de vocês.
