### ISSUE TITLE
Apache Kafka

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#52]
Apresente detalhes sobre o projeto, tais como:

* o que é o projeto?
* qual é ou quais são seus objetivos?
* qual a importância desse projeto para a fundação Apache e para o Software Livre como um todo?
* qual o status do projeto atualmente?
* qual a página oficial do projeto?

Para realizar essa _issue_, utilize o arquivo `apache/kafka.md`

**Comment by HCuri1** [comment]
Bom dia! Eu, José Vitor e Paulo Eduardo gostariamos de trabalhar nessa Issue.

**Comment by paulojunior-ufla** [comment]
Olá, @HCuri1. Ok, aguardo o PR de vocês.

**Comment by brenocb00** [comment]
Oi, @HCuri1. Estou sem grupo, posso fazer com vocês?

**Comment by natharaujos** [comment]
Opa, @HCuri1 . Se eu puder fazer parte do grupo também! Estou sem.

**Comment by HCuri1** [comment]
> Opa, @HCuri1 . Se eu puder fazer parte do grupo também! Estou sem.

Opa @natharaujos, o grupo preencheu com o @brenocb00. Mas caso não tenha problema para o @paulojunior-ufla, seria legal ter você no grupo.

**Comment by HCuri1** [comment]
> Oi, @HCuri1. Estou sem grupo, posso fazer com vocês?

Te mandei solicitação no Linkedin para trocarmos contato @brenocb00

**Comment by natharaujos** [comment]
Professor permitiu 5 integrantes no grupo, se não me engano. Amigo meu mandou mensagem pra ele! @paulojunior-ufla

**Comment by paulojunior-ufla** [comment]
Olá, @natharaujos. Se precisar, pode montar um grupo com 5 integrantes. Mais do que isso, eu já recomendo que façam 2 grupos de 3 e proponha uma nova issue.
