### ISSUE TITLE
Apache Maven

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#53]
Apresente detalhes sobre o projeto, tais como:

* o que é o projeto?
* qual é ou quais são seus objetivos?
* qual a importância desse projeto para a fundação Apache e para o Software Livre como um todo?
* qual o status do projeto atualmente?
* qual a página oficial do projeto?

Para realizar essa _issue_, utilize o arquivo `apache/maven.md`

**Comment by caiomtls** [comment]
Olá. Meu grupo gostaria de trabalhar nessa issue.

Integrantes: Caio, Felipe, Jonathas, Luiz Eduardo e Marco.

**Comment by paulojunior-ufla** [comment]
Olá, @caiomtls. Ótimo, aguardo o PR de vocês!
