### ISSUE TITLE
Apache Openoffice

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#54]
Apresente detalhes sobre o projeto, tais como:

* o que é o projeto?
* qual é ou quais são seus objetivos?
* qual a importância desse projeto para a fundação Apache e para o Software Livre como um todo?
* qual o status do projeto atualmente?
* qual a página oficial do projeto?

Para realizar essa _issue_, utilize o arquivo `apache/openoffice.md`

**Comment by rock051** [comment]
Meu grupo vai trabalhar nessa issue Apache Openoffice #54 !!!
Fernando, Valter é Claudio.

**Comment by paulojunior-ufla** [comment]
Olá, @rock051. Ansioso para saber mais sobre esse projeto Apache. Aguardo o PR de vocês.
