### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#55]
Apresente detalhes sobre o projeto, tais como:

* o que é o projeto?
* qual é ou quais são seus objetivos?
* qual a importância desse projeto para a fundação Apache e para o Software Livre como um todo?
* qual o status do projeto atualmente?
* qual a página oficial do projeto?

Para realizar essa _issue_, utilize o arquivo `apache/apache-license.md`

**Comment by taianers** [comment]
Olá, meu grupo formado por:
- Eduardo Carvalho Leite
- Iorrana Maria do Nascimento
- Luiz Carlos Bessa de Lima
- Taiane Rodrigues de Sousa

Gostaria de trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
Tudo bem, @taianers. Podem prosseguir!
