### ISSUE TITLE
Curiosidades e polêmicas

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#56]
Apresente as principais curiosidades e polêmicas acerca desta personalidade, seja no aspecto histórico, das pessoas envolvidas, dos principais projetos, etc. Tente ser o mais objetivo possível, citando apenas fatos comprovados e publicamente divulgados.

Para realizar essa _issue_, utilize o arquivo `apache/curiosidades-e-polemicas.md`

**Comment by jamillydanielle** [comment]
Tenho interesse em desenvolver esta feature

**Comment by paulojunior-ufla** [comment]
Olá @jamillydanielle. Tudo bem, aguardo seu PR.
