### ISSUE TITLE
Prêmios e reconhecimentos

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#57]
Apresente os principais prêmios e reconhecimentos recebidos por esta personalidade, disponíveis publicamente, com comentários que descrevam onde e quando ocorreu a premiação e sobre qual tipo de contribuição ela se referia.

Para realizar essa _issue_, utilize o arquivo `apache/premios-e-reconhecimentos.md`

**Comment by IsabelaCJesus** [comment]
Olá! Meu grupo gostaria de trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @IsabelaCJesus. Ok, sigam em frente!
