### ISSUE TITLE
Produções (artigos, livros, documentários, etc.)

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#58]
Apresente as principais produções desta personalidade ou a respeito dela, tais como livros ou artigos, documentários, etc. Procure oferecer referências (links) para que se possa chegar até estas produções.

Para realizar essa _issue_, utilize o arquivo `apache/producao.md`

**Comment by juliacteixeira** [comment]
Olá,  eu e meu grupo gostaríamos de fazer esse tópico.

**Comment by paulojunior-ufla** [comment]
Olá, @juliacteixeira. Combinado! Aguardo seu PR.
