### ISSUE TITLE
A licença GPL (GNU Public License)

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#6]
Detalhes sobre sua relação com o movimento de Software Livre, em especial sobre a licença GPL (_GNU Public License_): 

- o que é a GPL?
- qual é ou quais são seus objetivos?
- como ela se relaciona com o Software Livre?
- qual o status do projeto atualmente?

Para realizar essa _issue_, utilize o arquivo `stallman/gpl.md`

**Comment by arthurmmaia** [comment]
Bom dia Paulo, gostaria de realizar essa issue. Atualmente estou sem grupo, portanto no momento farei o trabalho sozinho, porém estou aberto a interessados em formar um grupo.

**Comment by paulojunior-ufla** [comment]
Olá, @arthurmmaia. Pode ser. Obrigado por se disponibilizar a incluir outras pessoas no grupo.
