### ISSUE TITLE
Polêmicas

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#7]
Apresente as principais polêmicas em que a personalidade esteve envolvida, seja no aspecto pessoal, acadêmico ou profissional. Tente ser o mais objetivo possível, citando apenas fatos comprovados e publicamente divulgados.

Para realizar essa _issue_, utilize o arquivo `stallman/polemicas.md`

**Comment by lu-nasc** [comment]
Boa noite, gostaria de trabalhar nessa issue, sendo que atualmente não possuo dupla ou mais pessoas estou aberto a quem quiser colaborar. 
<img src="https://user-images.githubusercontent.com/66646288/182981314-f72bf025-318e-4641-9853-9655af965605.png" width="100" height="90"/>

Buscarei especificar na seguinte construção:
1. Breve texto descritivo do material fonte.
2. Descrição curta que contextualize a polemica respondendo as perguntas:
 * *o que aconteceu?*
 * *como aconteceu?*
 * *quem estava envolvido?*
 * *quando ocorreu?*
3. Referência a fonte que comprova a polemica.

**Comment by paulojunior-ufla** [comment]
Legal, @lu-nasc. Gostei da proposta. Já marquei essa _issue_ como `equipe-aceita-integrante`

**Comment by Space-G** [comment]
@lu-nasc a nossa equipe tem interesse em colaborar, tá de boa?
Sou a Kali, tô com o Marcos Salles e o Sérgio Garcia

**Comment by lu-nasc** [comment]
claro, sejam bem vindes

**Comment by paulojunior-ufla** [comment]
@lu-nasc e @Space-G, não recebi um PR de vocês até o momento. Está tudo bem? Precisam de alguma ajuda?

**Comment by Space-G** [comment]
Eu preciso de ajuda pra organizar meus horários 😢 
Desculpas, professor. Muitas entregas de outros trabalhos e de minha IC me fizeram priorizar outros trabalhos para atingir suas deadlines, mas amanhã garanto que dedicarei a maior parte do dia para este projeto.

**Comment by lu-nasc** [comment]
Esta bem sim, só temos tidos dificuldade de encontrar devido aos horários e outras demandas.

**Comment by paulojunior-ufla** [comment]
Certo, @Space-G e @lu-nasc. Qualquer coisa, estou à disposição.
