### ISSUE TITLE
Curiosidades

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#8]
Apresente as principais curiosidades acerca desta personalidade, seja no aspecto pessoal, acadêmico ou profissional. 

Para realizar essa _issue_, utilize o arquivo `stallman/curiosidades.md`

**Comment by jmmarmontelo** [comment]
Olá meu grupo (João, Samir e Gabriela) tem interesse em realizar esta issue.

**Comment by paulojunior-ufla** [comment]
Olá, @jmmarmontelo. OK, combinado!
