### ISSUE TITLE
Produção (livros, artigos, programas de computador, etc)

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/personalidades-sl#9]
Apresente as principais produções desta personalidade, tais como livros ou artigos escritos por ela, programas de computador, etc. Procure oferecer referências (links) para que se possa chegar até estas produções.

Para realizar essa _issue_, utilize o arquivo `stallman/producao.md`

**Comment by JhoPhis** [comment]
Olá Paulo, eu (João Plínio) e o meu grupo (Luísa Maria e Arthur Hauck) gostaria de contribuir com essa issue.

**Comment by paulojunior-ufla** [comment]
Olá @JhoPhis. Ótimo, podem prosseguir.
